accounts/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView


app_name = 'accounts'
urlpatterns = [
    path('login/',
        LoginView.as_view(
            redirect_authenticated_user=True,
            template_name='registration/login.html'
        ),
        name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("signup/", login_required(views.SignUpView.as_view()), name="signup"),
    path("mypage/",login_required(views.user_page), name="mypage"),
]

time_logging/urls.py
from django.urls import path
from . import views
from .views  import (
    Enter, Add, Exit, ExitExecute,
)
from django.contrib.auth.decorators import login_required

app_name = 'time_logging'
urlpatterns = [
    path('', views.index, name='index'),
    path('enter/', Enter.as_view(), name='enter'),
    path('exit/', Exit.as_view(), name='exit'),
    path('exit/<int:pk>/', ExitExecute.as_view(), name='exit_execute'),
    path('add/', Add.as_view(), name='add'),
    path('use/', views.use, name='use'),
    path('message/<str:type>/', views.message, name='message'),
]

time_logging/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import RegexValidator

class TimeLog(models.Model):
    is_exit=models.BooleanField(default=False)
    faculty = models.CharField(max_length=20)
    attribute = models.CharField(max_length=20)
    student_number = models.CharField(max_length=10,blank = True,
                                    null=True,
                                    validators=[RegexValidator(r'^[0-9]{8}$')],
                                    )
    name = models.CharField(max_length=50,blank = True,null=True)
    start_date = models.DateTimeField(null=True, blank=True,)
    end_date = models.DateTimeField(null=True, blank=True,)
    enter=models.DateTimeField()
    exit=models.DateTimeField(blank = True,null=True)

    def __str__(self):
        text = f"学部：{self.faculty}、属性：{self.attribute}、入室時間：{timezone.localtime(self.enter)}"
        return text

time_logging/forms.py
from django import forms
from .models import TimeLog


class EnterForm(forms.Form):
    faculties = [
        ('情報', '情報'),
        ('アニメ・マンガ', 'アニメ・マンガ'),
        ('事業創造', '事業創造'),
        ('その他', 'その他'),
    ]
    faculty = forms.ChoiceField(
        label='学部',
        choices=faculties,
        initial='情報',
        widget=forms.RadioSelect(attrs={'class':'input-radio'}),
        required=True,
    )

    attributes = [
        ('学生', '学生'),
        ('教員', '教員'),
        ('職員', '職員'),
        ('その他', 'その他'),
    ]
    attribute = forms.ChoiceField(
        label='所属',
        choices=attributes,
        initial='学生',
        widget=forms.RadioSelect(attrs={'class':'input-radio'}),
        required=True,
    )

    student_number = forms.CharField(
        label='学籍番号',
        required=False,
        widget=forms.TextInput(attrs={'placeholder': '20232024（数字八桁）'}),
        min_length=8,
        max_length=8,
        strip=True,
        
        )
    
    name = forms.CharField(
        label='氏名',
        required=False,
        #help_text= '学生は任意',
        widget=forms.TextInput(attrs={'placeholder': '開志専太'}),
        min_length=1,
        max_length=48,
        strip=True,
        
        )
    
class AddForm(EnterForm):
    
    enter =  forms.DateTimeField(
        label='入室時間',
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        required=True,
        
        )

    
    exit = forms.DateTimeField(
        label='退室時間',
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        required=True,
        
        )
    

time_logging/views.py
from typing import Any
from django.shortcuts import render, get_object_or_404, redirect
from .forms import (
    EnterForm, AddForm, 
)
from django.views.generic import (
    TemplateView, ListView, UpdateView, DeleteView
)
from .models import TimeLog
from django.utils import timezone
from django.utils.timezone import timedelta
from django.db.models import Q
from django.http import HttpResponse
import re
from django.urls import reverse


def is_number(value):
    result = False
    if (re.match(r'^[0-9]*$', str(value)) != None):
        result = True
    return result


def message(request, type):
    title = 'もう一度やり直してください'
    text = ''
    label = 'ログインする'
    name = 'accounts:login'

    if type == 'signup':
        title = '登録が完了しました'
        text = 'ユーザーの新規登録が完了しました。以下のボタンからログインしてください。'
    elif type == 'enter':
        title = '入室しました'
        text = '入室の時間が記録されました。以下のボタンからホームに戻ってください'
        label = 'ホームに戻る'
        name = 'time_logging:index'
    elif type == 'exit':
        title = '退室しました'
        text = '退室の時間が記録されました。以下のボタンからホームに戻ってください'
        label = 'ホームに戻る'
        name = 'time_logging:index'
    elif type == 'add':
        title = '時間が記録されました'
        text = '入退室の時間が記録されました。以下のボタンからホームに戻ってください'
        label = 'ホームに戻る'
        name = 'time_logging:index'

    view_url = reverse(name)
    context ={
        "title":title,
        "text":text,
        "label":label,
        "url": view_url,
        }
    return render(request, 'time_logging/message.html', context )



def index(request):
    return render(request, 'time_logging/index.html')


class Enter(TemplateView):

    template_name='time_logging/forms.html'

    def __init__(self):
        self.param = {
            'error':'',
            'back':'time_logging:index',
            'msg':'入室される方は必要な情報を入力し確定を押してください',
            'urlName':'time_logging:enter',
            'forms':EnterForm
        }
    
    def get(self, request):
        return self.render_to_response(self.param)
    
    def post(self, request):
        faculty = request.POST.get('faculty')
        attribute = request.POST.get('attribute')
        student_number = request.POST.get('student_number')
        name = request.POST.get('name')
        enter = timezone.localtime(timezone.now())

        error = None

        if student_number == '' and name == '':
            error = '学籍番号か氏名を入力してください'
        elif is_number(student_number) == False:
            error = '正しく学生番号を入力してください'

        if error is None:
            timelog = TimeLog(
                faculty = faculty, attribute = attribute, 
                student_number = student_number, 
                name = name, enter = enter,
                )
            timelog.save()

            url = reverse('time_logging:message', kwargs={'type': 'enter'})
            
            return redirect(url)

        self.param['error'] = error
        self.param['forms'] = EnterForm(request.POST)#前のポスト内容を残す
        return self.render_to_response(self.param)


class Add(TemplateView):

    template_name='time_logging/forms.html'

    def __init__(self):
        self.param = {
            'error':'',
            'back':'time_logging:index',
            'msg':'あとから時間を記録する方は、必要な情報を入力し確定を押してください',
            'urlName':'time_logging:add',
            'forms':AddForm
        }
    
    def get(self, request):
        return self.render_to_response(self.param)
    
    def post(self, request):
        faculty = request.POST.get('faculty')
        attribute = request.POST.get('attribute')
        student_number = request.POST.get('student_number')
        name = request.POST.get('name')
        enter = request.POST.get('enter')
        exit = request.POST.get('exit')

        error = None

        if exit < enter:
            error = '日時を正しく入力してください'
        elif student_number == '' and name == '':
            error = '学生番号か氏名を入力してください'
        elif is_number(student_number) == False:
            error = '正しく学生番号を入力してください'
        # elif enter.day != exit.day:
        #     error = '同じ日付を入力してください'

        if error is None:
            timelog = TimeLog(
                is_exit = True,
                faculty = faculty, attribute = attribute, 
                student_number = student_number, 
                name = name, enter = enter,
                exit = exit,
                )
            timelog.save()
            url = reverse('time_logging:message', kwargs={'type': 'add'})
            return redirect(url)

        self.param['error'] = error
        self.param['forms'] = AddForm(request.POST)#前のポスト内容を残す
        return self.render_to_response(self.param)


class Exit(ListView):

    template_name = 'time_logging/exit.html'
    
    def get_queryset(self): # 検索機能のために追加
        text = self.request.GET.get('text')
        sort = self.request.GET.get('sort', 'id')
        if not(sort == 'id' or sort == '-id'):
            sort = 'id'

        today = timezone.localtime(timezone.now()).date()

        if text:
            data = TimeLog.objects.filter(
                Q(is_exit=False) & 
                (Q(student_number__contains=text) | Q(name__contains=text))
                & Q(enter__date=today)
            )
        else:
            data = TimeLog.objects.filter(is_exit=False, enter__date=today) 

        return data.order_by(sort)


class ExitExecute(TemplateView):
    template_name='time_logging/exit_do.html'

    def __init__(self):
        self.param = {
            'error':'',
            'data':None,
        }
    
    def get(self, request, pk):
        self.param['data'] = get_object_or_404(TimeLog, pk=pk)
        return self.render_to_response(self.param)
    
    def post(self, request, pk):
        check_id = int(request.POST['id'])
        pk = int(pk)
        log = get_object_or_404(TimeLog, pk=pk)
        self.param['data'] = log

        if check_id == pk:
            log.is_exit = True
            log.exit = timezone.localtime(timezone.now())
            log.save()
            
            url = reverse('time_logging:message', kwargs={'type': 'exit'})
            return redirect(url)

        self.param['error'] = 'もう一度入力してください'
        return self.render_to_response(self.param)

    


def use(request):
    return render(request, 'time_logging/use.html')

time_logging/templates/time_logging/exit.html
{% extends 'base.html' %}

{% block title %}EXIT{% endblock %}

{% block header %}
<div class="notice tb-center">
    自分の列の退出ボタンを押して退室してください
</div>
{% endblock %}


{% block content %}
<div class="text-start">
    <p><a class="back-page" href="{% url 'time_logging:index' %}">←HOMEに戻る</a></p>
</div>

<div style="height: 32px;"></div>


<form method="get">
    <div class="search-form-box">
        <span class="search-form">
            <input id="text" value="{{ request.GET.text }}" 
            name="text" type="text" placeholder="学籍番号・氏名">
        </span>
        <div style="width: 8px;"></div>
        <input type="submit" value="検索する">
    </div>
    <div class="sort-box">
        {% if request.GET.sort == '-id' %}
        <div>
            <button type="submit" value="id" 
            name="sort" id="sort" class="sort-b">
                ↑
            </button>
        </div>
        {% else %}
        <div>
            <button type="submit" value="-id" 
            name="sort" id="sort" class="sort-b">
            ↓
            </button>
        </div>
        {% endif %}
    </div>
</form>


<div style="height: 8px;"></div>

<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>学部</th>
            <th>属性</th>
            <th>学籍番号</th>
            <th>氏名</th>
            <th>入室時間</th>
            <th>退出時間</th>
        </tr>
    </thead>
    <div class="exit-list">
        <tr style="color:rgb(62, 130, 255);">
            <th>(例)0</th>
            <th>(例)情報</th>
            <th>(例)学生</th>
            <th>(例)2024</th>
            <th>(例)開志</th>
            <th>(例)09時00分</th>
            <th>(例)19時00分</th>
        </tr>

        {% for data in object_list %}
        <tr>
            <th>{{ data.id }}</th>
            <th>{{ data.faculty }}</th>
            <th>{{ data.attribute }}</th>
            <th>
                {% if data.student_number is not None %}
                {{ data.student_number }}
                {% endif %}
            </th>
            <th>
                {% if data.name is not None %}
                {{ data.name }}
                {% endif %}
            </th>

            <th>{{ data.enter | date:"H時i分"}}</th>
            <th>
                <a href="{% url 'time_logging:exit_execute' pk=data.id %}">
                    <button class="b-exit">退出する</button>
                </a>
            </th>
        </tr>
        {% endfor %}
    </div>
</table>


<div style="height: 32px;"></div>
<div class="text-start">
    <p><a href="{% url 'time_logging:index' %}">←HOMEに戻る</a></p>
</div>
<div style="height: 32px;"></div>
{% endblock %}

time_logging/templates/time_logging/exit_do.html
{% extends 'base.html' %}

{% block title %}ENTER{% endblock %}

{% block header %}
<div class="notice tb-center">
    確認してから退出を押してください
</div>
{% endblock %}

{% block error %}
{% if error != '' %}
    <div class="error">{{ error }}</div>
{% endif %}
{% endblock %}

{% block content %}

<div class="text-start">
    <p><a href="{% url 'time_logging:exit' %}">←戻る</a></p>
</div>

<div style="height: 24px;"></div>

<div class="wrap">
    <table>
        <tr>
            <th colspan="2"><label for="">入室情報</label></th>
        </tr>
    
        {% if data.student_number is None %}
            <tr>
                <th>氏名</th>
                <th>{{ data.name }}</th>
            </tr>
        {% else %}
            <tr>
                <th>学籍番号</th>
                <th>{{ data.student_number }}</th>
            </tr>
        {% endif %}
    
        <tr>
            <th>学部</th>
            <th>{{ data.faculty }}</th>
        </tr>
    
        <tr>
            <th>所属</th>
            <th>{{ data.attribute }}</th>
        </tr>
    
        <tr>
            <th>入室時間</th>
            <th>{{ data.enter | date:"H時i分" }}</th>
        </tr>
    </table>

    <form  method="post">
        {% csrf_token %}
        <input type="hidden" value="{{ data.id }}" name="id">
        <div style="height: 32px;"></div>
        <button type="submit" onclick="return confirm('退出しますか？')"  class="b-exit" >
            退出する
        </button>
    </form>
</div>


{% endblock %}

time_logging/templates/time_logging/forms.html
{% extends 'base.html' %}

{% block title %}ENTER{% endblock %}

{% block header %}
{% if msg != '' %}
<div class="notice tb-center">
    {{ msg }}
</div>
{% endif %}
{% endblock %}

{% block error %}
{% if error != '' %}
    <div class="error">{{ error }}</div>
{% endif %}
{% endblock %}

{% block content %}

{% if back != '' %}
<div class="text-start">
    <p><a href="{% url back %}">←HOMEに戻る</a></p>
</div>
{% endif %}

<div class="wrap centered-box">

    <form action="{% url urlName %}" method="post">
        {% csrf_token %}
        {{ forms.as_p }}
        <div style="height: 32px;"></div>
        <button type="submit" onclick="return confirm('確定しますか？')">確定する</button>
    </form>

    <div style="height: 48px;"></div>

</div>

{% endblock %}

time_logging/templates/time_logging/index.html
{% extends 'base.html' %}

{% block title %}HOME{% endblock %}

{% block header %}
<div class="notice tb-center">
    以下のボタンを押して入室/退室時間を記録してください
</div>
{% endblock %}

{% block content %}
<div style="height: 32px;"></div>
<div class="equal-intervals">
    <a href="{% url 'time_logging:enter' %}" class="box entry tb-center">
        入室する
    </a>

    <a href="{% url 'time_logging:exit' %}" class="box exit tb-center">
        退室する
    </a>
</div>

<div class="equal-intervals">
    <a href="{% url 'time_logging:use' %}" class="box how_to_use tb-center">
        使い方
    </a>

    <a href="{% url 'time_logging:add' %}" class="box other tb-center">
        追録
    </a>
</div>
{% endblock %} 

time_logging/templates/time_logging/message.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block content %}
<div class="wrap centered-box" >
    <h1>{{ title }}</h1>
    <p>{{ text }}</p>

    <div style="height: 12px;"></div>

    <div>
        <a href="{{ url }}">
            <button>{{ label }}</button>
        </a>
    </div>

    <div style="height: 48px;"></div>
</div>

{% endblock %} 

time_logging/templates/time_logging/use.html
{% extends 'base.html' %}

{% block title %}使い方{% endblock %}

{% block content %}
<div class="text-start">
    <p><a href="{% url 'time_logging:index' %}">←HOMEに戻る</a></p>
</div>

<div class="wrap centered-box" >
    <h1>使い方</h1>
    <h3 class="color-grey">入室する場合</h3>
    <p>ホーム画面から”入室する”と書かれた
        ボタンを押して、必要な情報を入力したのちに、”確定する”と書かれた
        ボタンを押してください。</p>
    <p>学生の場合は、学生番号か氏名を入力してください。</p>
    <p>学生の場合は、学生番号か氏名を入力してください。</p>
    <div style="height: 28px;"></div>

    <h3 class="color-grey">退室する場合</h3>
    <p>ホーム画面から”退出ボタン”を押して、自分の情報の行を選択し、退出すると書かれた
        ボタンを押してください。</p>
    <p>この際、学生番号と氏名を対象に、テーブル上のフォームから検索を行うことができます。</p>
    <div style="height: 28px;"></div>

    <h3 class="color-grey">あとから情報を入力する場合</h3>
    <p>ホーム画面から”追録ボタン”を押して、必要な情報を入力したのちに、”確定する”と書かれた
        ボタンを押してください。</p>
    <div style="height: 28px;"></div>

    <h3 class="color-grey">その他動作</h3>
    <p>データを削除したい、などの上記以外の操作が必要な場合は管理者に連絡してください。</p>

    <div style="height: 48px;"></div>
</div>

{% endblock %} 