accounts/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView


app_name = 'accounts'
urlpatterns = [
    path('login/',
        LoginView.as_view(
            redirect_authenticated_user=True,
            template_name='registration/login.html'
        ),
        name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("signup/", login_required(views.SignUpView.as_view()), name="signup"),
    path("mypage/",login_required(views.user_page), name="mypage"),
]

management/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required
from .views  import (
    Manage, Download, Analysis,
)

app_name = 'management'
urlpatterns = [
    path('', login_required(views.index), name='index'),
    path('list/', login_required(Manage.as_view()), name='list'),
    path('<int:log_id>/update/', login_required(views.ManageUpdate), name='update'),
    path('<int:log_id>/delete/', login_required(views.ManageDelete), name='delete'),
    path('download/', login_required(Download.as_view()), name='download'),
    path('analysis/', login_required(Analysis.as_view()), name='analysis'),
]

management/models.py
from django.db import models

# Create your models here.

management/forms.py
from django import forms


class DownloadForm(forms.Form):

    year = forms.IntegerField(
        label='年',
        required=True,
        widget=forms.NumberInput,
        min_value=2023,
        max_value=2100,
        disabled=False,
    )

    month = forms.IntegerField(
        label='月',
        required=True,
        widget=forms.NumberInput,
        min_value=1,
        max_value=12,
        disabled=False,
    )

management/views.py
from typing import Any
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import (
    TemplateView, 
)
from .forms import (
    DownloadForm,
)
from time_logging.models import TimeLog
from django.utils import timezone
from django.utils.timezone import timedelta
from django.db.models import Q
import csv
from django.http import HttpResponse
import re
import statistics


def DataGetForAnalysis(year=None, month=None, is_exit=True):
    now = timezone.localtime(timezone.now())
    if year is None or month is None:
        year = now.year
        month = now.month


    data = TimeLog.objects.filter(
        is_exit=is_exit, 
        enter__year=year, 
        enter__month=month,
    )

    weekday_japanese = {
        'Monday': '月',
        'Tuesday': '火',
        'Wednesday': '水',
        'Thursday': '木',
        'Friday': '金',
        'Saturday': '土',
        'Sunday': '日',
    }

    DataForAnalysis = []

    for i in data:
        i.exit = timezone.localtime(i.exit)
        i.enter = timezone.localtime(i.enter)
        if is_exit:
            duration = int((i.exit - i.enter).total_seconds() // 60)
            exit = f"{i.exit.hour}:{i.exit.minute}"
            if duration < 1:
                duration = 1

        else:
            duration = None
            exit = None

        enter = f"{i.enter.hour}:{i.enter.minute}"
        weekday = weekday_japanese.get(i.enter.strftime('%A'), '')

        DataForAnalysis.append({
            'id': i.id,
            'is_exit': i.is_exit,
            'year': i.enter.year,
            'month': i.enter.month,
            'day': i.enter.day,
            'weekday': weekday,
            'faculty': i.faculty,
            'attribute': i.attribute,
            'student_number': i.student_number,
            'name': i.name,
            'duration': duration,
            'enter': enter,
            'exit': exit,
        })

    return DataForAnalysis



def is_number(value):
    result = False
    if (re.match(r'^[0-9]*$', str(value)) != None):
        result = True
    return result

def is_int(s):
    try:
        int(s)
    except ValueError:
        return False
    else:
        return True



def index(request):
    return render(request, 'management/index.html')


class Analysis(TemplateView):

    template_name='management/analysis.html'

    def __init__(self):
        now = timezone.localtime(timezone.now())
        month = now.month
        self.param = {
            'error':'',
            'data':None,
            'month':month,
        }

    
    def get(self, request):
        if 'data_set' in request.session:
            data = self.request.session["data_set"]
            self.param['data'] = data
        return self.render_to_response(self.param)
    

    def post(self, request):
        check = request.POST.get('check')
        if check == '分析する':
            data_set = DataGetForAnalysis(is_exit=True)
            data = self.get_result_of_analysis(data_set)
            self.request.session["data_set"] = data
            self.param['data'] = data
        else:
            self.param['error'] = 'もう一度、やり直してください'
        
        return self.render_to_response(self.param)
    

    def get_result_of_analysis(self, data_set):
        student_count = 0
        other_count = 0
        info_faculty_count = 0
        other_faculty_count = 0
        durations = []

        weekdays = ['月', '火', '水', '木', '金']
        weekday_data = {day: {'count': 0, 'total_duration': 0} for day in weekdays}

        for record in data_set:
            # 属性が学生の合計利用者数と、その他の合計利用者数
            if record['attribute'] == '学生':
                student_count += 1
            else:
                other_count += 1

            # 学部が情報学部の合計利用者数、その他の学部の合計利用者数
            if record['faculty'] == '情報':
                info_faculty_count += 1
            else:
                other_faculty_count += 1

            # 利用時間（duration）
            duration = record['duration']
            durations.append(duration)

            # 曜日ごとのデータ集計
            week_day = record['weekday']
            if week_day in weekdays:
                weekday_data[week_day]['count'] += 1
                weekday_data[week_day]['total_duration'] += duration

        # 利用時間の合計、平均、最小値、最大値、中央値などの計算
        total_count = student_count + other_count
        total_duration = sum(durations)
        average_duration = int(statistics.mean(durations)) if durations else 0
        min_duration = min(durations) if durations else 0
        max_duration = max(durations) if durations else 0
        median_duration = statistics.median(durations) if durations else 0

        week_data_set = []

        # 曜日ごとの平均計算
        for day in weekdays:
            total_duration = weekday_data[day]['total_duration']
            week_data_set.append(round(total_duration))

        graph_data = self.data_for_graph(week_data_set)

        all_data = {
            'average_duration': average_duration,
            'total_duration': total_duration,
            'min_duration': min_duration,
            'max_duration': max_duration,
            'median_duration': median_duration,

            'total_count':total_count,
            'student_count': student_count,
            'other_count': other_count,
            'info_faculty_count': info_faculty_count,
            'other_faculty_count': other_faculty_count,

            'weekday_data': weekday_data,
            'graph_data': graph_data,

            'test': None,
        }

        return all_data
    

    def data_for_graph(self, data_set):
        total = sum(data_set)
        week_rates = []
        graph_data={}

        for data in data_set:
            if total != 0 :
                rate = round(data / total *100)
                rate = 10 * round(rate / 10)
            else:
                rate = 0
            week_rates.append(rate)

        for i in range(100, 9, -10):
            week_data = []
            for week_rate in week_rates:
                if week_rate >= i:
                    a = 1
                else:
                    a = 0
                week_data.append(a)
            graph_data[i] = week_data

        return graph_data





class Download(TemplateView):

    template_name='management/download.html'

    def __init__(self):
        self.param = {
            'error':'',
            'forms':DownloadForm,
        }
    
    def get(self, request):
        return self.render_to_response(self.param)
    
    def post(self, request):
        year = request.POST.get('year')
        month = request.POST.get('month')

        error = None

        if year == '' and month == '':
            error = 'ダウンロードする年と月を入力してください。'
        elif is_number(year) == False and is_number(month) == False:
            error = '正しく数字を入力してください'
        elif 1 > int(month) and int(month) > 13:
            error = '正しく月の数字を入力してください'
        elif 2000 > int(year) and int(year) > 2100:
            error = '正しく年の数字を入力してください'

        if error is None:
            titleDate = f"{year}-{month}"

            response = HttpResponse(
                content_type="text/csv",
                headers={"Content-Disposition": 'attachment; filename="Log-'+ titleDate +'.csv"'},
            )

            response.write('\ufeff'.encode('utf8'))
            writer = csv.writer(response)
            writer.writerow([
                "年", "月", "日", "曜日",
                "学部", "所属", "学籍番号", "氏名", 
                "利用時間(分)", "入室時間", "退出時間", 
            ])

            data = DataGetForAnalysis(year=year, month=month)

            for i in data:
                writer.writerow([
                    i['year'], i['month'], i['day'],
                    i['weekday'], i['faculty'], i['attribute'],
                    i['student_number'], i['name'], i['duration'],
                    i['enter'], i['exit']
                ])

            return response

        self.param['error'] = error
        self.param['forms'] = DownloadForm(request.POST)#前のポスト内容を残す
        return self.render_to_response(self.param)
    


class Manage(TemplateView):

    template_name='management/list.html'

    def __init__(self):
        self.param = {
            'error':'',
            'data': None,
        }
    
    def get(self, request):
        fiter = self.request.GET.get('exit', 'yet')
        if not(fiter == 'yet' or fiter == 'al'):
            fiter = 'yet'

        is_exit=False

        if fiter == 'yet':
            is_exit=False
        else:
            is_exit=True

        self.param['data'] = DataGetForAnalysis(is_exit=is_exit)
        return self.render_to_response(self.param)
    
    def post(self, request):
        faculty = request.POST.get('faculty')
        attribute = request.POST.get('attribute')
        student_number = request.POST.get('student_number')
        name = request.POST.get('name')
        enter = request.POST.get('enter')
        exit = request.POST.get('exit')

        error = None

        if exit < enter:
            error = '日時を正しく入力してください'
        elif student_number == '' and name == '':
            error = '学生番号か氏名を入力してください'
        elif is_number(student_number) == False:
            error = '正しく学生番号を入力してください'

        if error is None:
            timelog = TimeLog(
                is_exit = True,
                faculty = faculty, attribute = attribute, 
                student_number = student_number, 
                name = name, enter = enter,
                exit = exit,
                )
            timelog.save()
            return redirect(to='management:list')

        self.param['error'] = error
        return self.render_to_response(self.param)


def ManageUpdate(request, log_id):
    if(request.method == "POST"):
        duration = request.POST.get('duration')

        if(duration is not None and is_int(duration) and is_int(log_id)):
            log = get_object_or_404(TimeLog, pk=log_id)
            duration = int(duration)

management/templates/management/analysis.html
{% extends 'base_manager.html' %}
{% load static %}
{% block title %}{{ user.last_name }} {{ user.first_name }}{% endblock %}


{% block error %}
{% if error != '' %}
<div style="height: 32px;"></div>
<div class="error">{{ error }}</div>
{% endif %}
{% endblock %}


{% block content %}
<div style="height: 12px;"></div>

{% if data == None %}
<div class="wrap centered-box">
    <h1>{{ month }}月の利用分析</h1>
    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="check" id="check" value="分析する">
        <div style="height: 32px;"></div>
        <button type="submit">{{ month }}月のデータを分析する</button>
    </form>
</div>
{% else %}
<div class="chart-wrap">
<!-- ーーーーーーーーーーーーーーーーーーーーーーーーーーーー -->
<!-- ーーーーーーーーーーーーーーーーーーーーーーーーーーーー -->
<!-- ーーーーーーーーーーーーーーーーーーーーーーーーーーーー -->

<div class="wrap centered-box">
    <h1>{{ month }}月の利用分析</h1>

    <div style="height:24px;"></div>

    <table>
        <tr>
            <th colspan="2"><label for="">利用時間</label></th>
        </tr>

        <tr>
            <th>平均</th>
            <th>{{data.average_duration}}分</th>
        </tr>

        <tr>
            <th>合計</th>
            <th>{{data.total_duration}}分</th>
        </tr>

        <tr>
            <th>最小</th>
            <th>{{data.min_duration}}分</th>
        </tr>

        <tr>
            <th>最大</th>
            <th>{{data.max_duration}}分</th>
        </tr>

        <tr>
            <th>中央値</th>
            <th>{{data.median_duration}}分</th>
        </tr>

    </table>

    <div style="height:28px;"></div>

    <table>
        <tr>
            <th colspan="2"><label for="">利用人数</label></th>
        </tr>

        <tr>
            <th>合計</th>
            <th>{{data.total_count}}人</th>
        </tr>

        <tr>
            <th>生徒</th>
            <th>{{data.student_count}}人</th>
        </tr>

        <tr>
            <th>教員・職員等</th>
            <th>{{data.other_count}}人</th>
        </tr>

        <tr>
            <th>情報学部</th>
            <th>{{data.info_faculty_count}}人</th>
        </tr>

        <tr>
            <th>その他学部</th>
            <th>{{data.other_faculty_count}}人</th>
        </tr>

    </table>

    <div style="height:28px;"></div>

    <table>
        <tr>
            <th>曜日</th>
            <th>人数</th>
            <th>合計</th>
            <th>平均</th>
        </tr>
        {% for week, data in data.weekday_data.items %}
            <tr>
                <th>{{ week }}</th>
                <th>{{ data.count }}人</th>
                <th>{{ data.total_duration }}分</th>
                <th>{{ data.average_duration }}分</th>
            </tr>
        {% endfor %}
    </table>

    <div style="height: 32px;"></div>

    <h1>曜日利用割合</h1>
</div>
    <div class="barchart">
        <table>
            <tbody>
                {% for p, data in data.graph_data.items %}
                <tr>
                    <td class="barchart-td-t">{{ p }}</td>
                    {% for i in data %}
                        {% if i == 1 %}
                        <td><div class="barchart-blue"></div></td>
                        {% else %}
                        <td></td>
                        {% endif %}
                    {% endfor %}
                </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <td class="barchart-td-t">(%)</td>
                    <th>月</th>
                    <th>火</th>
                    <th>水</th>
                    <th>木</th>
                    <th>金</th>
                </tr>
            </tfoot>
        </table> 
    </div>

</div>

<div style="height: 32px;"></div>

<div class="wrap centered-box">
    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="check" id="check" value="分析する">
        <div style="height: 32px;"></div>
        <button type="submit">最新のデータで分析する</button>
    </form>
</div>
{% endif %}
<!-- ーーーーーーーーーーーーーーーーーーーーーーーーーーーー -->
<!-- ーーーーーーーーーーーーーーーーーーーーーーーーーーーー -->
<!-- ーーーーーーーーーーーーーーーーーーーーーーーーーーーー -->



<div style="height: 48px;"></div>
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}

management/templates/management/download.html
{% extends 'base_manager.html' %}
{% load static %}
{% block title %}{{ user.last_name }} {{ user.first_name }}{% endblock %}

{% block header %}
<header>
    <label class="header-l">こんにちは、{{ user.last_name }} {{ user.first_name }} さん</label>

    <form action="{% url 'accounts:logout' %}" method="post">
        {% csrf_token %}
        <input type="image"  onclick="return confirm('ログアウトしますか？')"
        id="image" alt="logout" src="{% static 'img/logout.png' %}" 
        class="logout-img">
    </form>

    <div style="width: 48px;"></div>

</header>
{% endblock %}


{% block error %}
{% if error != '' %}
<div style="height: 36px;"></div>
<div class="error">{{ error }}</div>
{% endif %}
{% endblock %}

{% block content %}
<div style="height: 12px;"></div>

<div class="wrap centered-box">
    <h1>ダウンロード</h1>
    <p>
        入退室の記録をCSVファイルでダウンロードします。
    </p>
    <p class="p-red">CSVファイルはエクセルやスプレッドシートで開くことができます。</p>
    <form method="post">
        {% csrf_token %}
        {{ forms.as_p }}
        <div style="height: 32px;"></div>
        <button type="submit">ダウンロードする</button>
    </form>

    <div style="height: 48px;"></div>

</div>

<div style="height: 48px;"></div>

<script src="{% static 'js/script.js' %}"></script>

{% endblock %}

management/templates/management/index.html
{% extends 'base_manager.html' %}
{% load static %}
{% block title %}{{ user.last_name }} {{ user.first_name }}{% endblock %}

{% block header %}
<header>
    <label class="header-l">こんにちは、{{ user.last_name }} {{ user.first_name }} さん</label>

    <form action="{% url 'accounts:logout' %}" method="post">
        {% csrf_token %}
        <input type="image"  onclick="return confirm('ログアウトしますか？')"
        id="image" alt="logout" src="{% static 'img/logout.png' %}" 
        class="logout-img">
    </form>

    <div style="width: 48px;"></div>

</header>
{% endblock %}


{% block content %}
<div style="height: 12px;"></div>
<div class="wrap centered-box">
    <h1>機能一覧</h1>

    <a href="{% url 'management:list' %}">
        <div class="manage-index">
            <div style="width: 20px;"></div>
            <img src="{% static 'img/list.png' %}" alt="">
            <div style="width: 20px;"></div>
            <p>一覧表示・編集</p>
        </div>
    </a>

    <div style="height: 40px;"></div>


    <a href="{% url 'management:analysis' %}">
        <div class="manage-index">
            <div style="width: 20px;"></div>
            <img src="{% static 'img/barchart.png' %}" alt="">
            <div style="width: 20px;"></div>
            <p>データ分析</p>
        </div>
    </a>

    <div style="height: 40px;"></div>

    <a href="{% url 'management:download' %}">
        <div class="manage-index">
            <div style="width: 20px;"></div>
            <img src="{% static 'img/download.png' %}" alt="">
            <div style="width: 20px;"></div>
            <p>データダウンロード</p>
        </div>
    </a>

    <div style="height: 40px;"></div>

    <a href="{% url 'accounts:mypage' %}">
        <div class="manage-index">
            <div style="width: 20px;"></div>
            <img src="{% static 'img/user.png' %}" alt="">
            <div style="width: 20px;"></div>
            <p>ユーザー画面</p>
        </div>
    </a>

    <div style="height: 30px;"></div>
</div>

<div style="height: 48px;"></div>
<script src="{% static 'js/script.js' %}"></script>

{% endblock %}

management/templates/management/list.html
{% extends 'base_manager.html' %}
{% load static %}
{% block title %}{{ user.last_name }} {{ user.first_name }}{% endblock %}

{% block header %}
<header>
    <label class="header-l">こんにちは、{{ user.last_name }} {{ user.first_name }} さん</label>

    <form action="{% url 'accounts:logout' %}" method="post">
        {% csrf_token %}
        <input type="image"  onclick="return confirm('ログアウトしますか？')"
        id="image" alt="logout" src="{% static 'img/logout.png' %}" 
        class="logout-img">
    </form>

    <div style="width: 48px;"></div>

</header>
{% endblock %}


{% block error %}
{% if error != '' %}
<div class="error">{{ error }}</div>
{% endif %}
{% endblock %}

{% block content %}
<div style="height: 48px;"></div>

<div class="over-scroll-center">
    <form method="get">

        <div class="sort-box">
            
            {% if request.GET.exit == 'al' %}
            <div>
                <button type="submit" value="yet" name="exit" id="exit" class="sort-b">
                    退出済
                </button>
            </div>
            {% else %}
            <div>
                <button type="submit" value="al" name="exit" id="exit" class="sort-b">
                    未退出
                </button>
            </div>
            {% endif %}
        </div>
    </form>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>年</th>
                <th>月</th>
                <th>日</th>
                <th>曜日</th>
                <th>学部</th>
                <th>属性</th>
                <th>学籍番号</th>
                <th>氏名</th>
                <th>入室時間</th>
                <th>退出時間</th>
                <th>利用時間(分)</th>
                <th>削除</th>
            </tr>
        </thead>
        {% for i in data %}
        </tr>
            <th>{{ i.id }}</th>
            <th>{{ i.year }}</th>
            <th>{{ i.month }}</th>
            <th>{{ i.day }}</th>
            <th>{{ i.weekday }}</th>
            <th>{{ i.faculty }}</th>
            <th>{{ i.attribute }}</th>
            <th>
                {% if i.student_number is not None %}
                {{ i.student_number }}
                {% endif %}
            </th>
            <th>
                {% if i.name is not None %}
                {{ i.name }}
                {% endif %}
            </th>
            <th>{{ i.enter }}</th>
            <th>
                {% if i.exit is  None %}
                未退出
                {% else %}
                {{ i.exit }}
                {% endif %}
            </th>
            <th>
                {% if i.is_exit == False %}
                <form action="{% url 'management:update' i.id %}" method="post">
                    {% csrf_token %}
                    <input type="number" name="duration" id="duration" placeholder="例：1" min="1" max="600" />
                    <button class="sort-b" type="submit" onclick="return confirm('時間を設定しますか？')">時間設定</button>
                </form>
                {% else %}
                {{ i.duration }}
                {% endif %}
            </th>
            <th>
                <form action="{% url 'management:delete' i.id %}" method="post">
                    {% csrf_token %}
                    <button class="b-exit" type="submit" onclick="return confirm('データを削除しますか？この操作は取り消せません。')">
                        削除する
                    </button>
                </form>
            </th>
        </tr>
        {% endfor %}
    </table>
</div>

<div style="height: 48px;"></div>


<script src="{% static 'js/script.js' %}"></script>

{% endblock %}