accounts/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView


app_name = 'accounts'
urlpatterns = [
    path('login/',
        LoginView.as_view(
            redirect_authenticated_user=True,
            template_name='registration/login.html'
        ),
        name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("signup/", login_required(views.SignUpView.as_view()), name="signup"),
    path("mypage/",login_required(views.user_page), name="mypage"),
]

management/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required
from .views  import (
    Manage, Download, Analysis,
)

app_name = 'management'
urlpatterns = [
    path('', login_required(views.index), name='index'),
    path('list/', login_required(Manage.as_view()), name='list'),
    path('<int:log_id>/update/', login_required(views.ManageUpdate), name='update'),
    path('<int:log_id>/delete/', login_required(views.ManageDelete), name='delete'),
    path('download/', login_required(Download.as_view()), name='download'),
    path('analysis/', login_required(Analysis.as_view()), name='analysis'),
]

time_logging/urls.py
from django.urls import path
from . import views
from .views  import (
    Enter, Add, Exit, ExitExecute,
)
from django.contrib.auth.decorators import login_required

app_name = 'time_logging'
urlpatterns = [
    path('', views.index, name='index'),
    path('enter/', Enter.as_view(), name='enter'),
    path('exit/', Exit.as_view(), name='exit'),
    path('exit/<int:pk>/', ExitExecute.as_view(), name='exit_execute'),
    path('add/', Add.as_view(), name='add'),
    path('use/', views.use, name='use'),
    path('message/<str:type>/', views.message, name='message'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <link rel="icon" href="{% static 'img/icon.png' %}" sizes="any">
    <link rel="apple-touch-icon" href="{% static 'img/icon.png' %}">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Brainstor Meeting Web Application">

    <title>{% block title %}{% endblock %} - Time Logging</title>
    <!-- ページタイトルをブロックとして定義し、各テンプレートでカスタマイズ可能にする -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>

    {% block header %}{% endblock %}
    
    {% block hamburger %}{% endblock %}

    <main>
        {% block error %}{% endblock %}
        {% block content %}
        <p>※コンテンツがありません。</p>
        {% endblock %}
    </main>

    <footer>

        <div>
            <p class="p-heading">Time Logging</p>
        </div>

        <div>
            <nav>

                <p>
                    <a href="{% url 'time_logging:use' %}">
                        使い方
                    </a>
                </p>
                <p>|</p>
                <p>
                    <a href="{% url 'management:index' %}">
                        管理者画面
                    </a>
                </p>

            </nav>
        </div>

        <div>
            <img src="{% static 'img/icon.png' %}" alt="現在の管理者">
        </div>

        <div style="height: 12px;"></div>

        <p>Made by KS-PF| 2023~2024</p>
        <p>All rights reserved</p>

        <div style="height: 32px;"></div>

    </footer>

</body>

</html>

templates/base_manager.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <link rel="icon" href="{% static 'img/icon.png' %}" sizes="any">
    <link rel="apple-touch-icon" href="{% static 'img/icon.png' %}">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Brainstor Meeting Web Application">

    <title>{% block title %}{% endblock %} - Time Log Manager</title>
    <link rel="stylesheet" href="{% static 'css/style_manager.css' %}">
</head>

<body>    
    <div id="hamburger" class="">
        <a class="hamburger-button" onmouseover="HamburgerIn();">
            <span class="hamburger-line hamburger-line-t"></span>
            <span class="hamburger-line hamburger-line-m"></span>
            <span class="hamburger-line hamburger-line-b"></span>
        </a>
        <div class="hamburger-content">
            <div style="height: 85px;"></div>
    
            <a href="{% url 'management:index' %}">
                <div  class="iconbar-icons-label">
                    <p>ホーム</p>
                </div>
            </a>
        
            <div style="height: 15px;"></div>
    
            <a href="{% url 'management:list' %}">
                <div  class="iconbar-icons-label">
                    <p>記録一覧</p>
                </div>
            </a>
        
            <div style="height: 15px;"></div>
            
            <a href="{% url 'management:analysis' %}">
                <div  class="iconbar-icons-label">
                    <p>分析</p>
                </div>
            </a>
        
            <div style="height: 15px;"></div>

            <a href="{% url 'management:download' %}">
                <div  class="iconbar-icons-label">
                    <p>ダウンロード</p>
                </div>
            </a>
        
            <div style="height: 15px;"></div>
    
    
            <a href="{% url 'accounts:mypage' %}">
                <div  class="iconbar-icons-label">
                    <p>ユーザー管理</p>
                </div>
            </a>

    
    
        </div>
        <a class="hamburger-out" onclick="HamburgerOut();"></a>
    </div>

    <div class="main-iconbar-flex">

        <div  class="main-iconbar-flex-main-content-l">
            <div style="height: 85px;"></div>
        
            <a href="{% url 'management:index' %}">
                <div  class="iconbar-icons-div">
                    <img src="{% static 'img/home.png' %}" alt="ホーム" class="iconbar-icons">
                </div>
            </a>
        
            <div style="height: 15px;"></div>
        
            <a href="{% url 'management:list' %}">
                <div  class="iconbar-icons-div">
                    <img src="{% static 'img/list.png' %}" alt="一覧" class="iconbar-icons">
                </div>
            </a>
        
            <div style="height: 15px;"></div>
        
            <a href="{% url 'management:analysis' %}">
                <div  class="iconbar-icons-div">
                    <img src="{% static 'img/barchart.png' %}" alt="分析" class="iconbar-icons">
                </div>
            </a>
        
            <div style="height: 15px;"></div>

            <a href="{% url 'management:download' %}">
                <div  class="iconbar-icons-div">
                    <img src="{% static 'img/download.png' %}" alt="ダウンロード" class="iconbar-icons">
                </div>
            </a>
        
            <div style="height: 15px;"></div>
        
            <a href="{% url 'accounts:mypage' %}">
                <div  class="iconbar-icons-div">
                    <img src="{% static 'img/user.png' %}" alt="ユーザー" class="iconbar-icons">
                </div>
            </a>
        
            <div style="height: 15px;"></div>
        
        
        
        </div>
        
        <div style="width: 65px;"></div>

        <div class="main-iconbar-flex-main-content-r">

            <header>
                <div style="width: 48px;"></div>
            
                <label class="header-l">こんにちは、{{ user.last_name }} {{ user.first_name }} さん</label>
            
                <form action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <input type="image"  onclick="return confirm('ログアウトしますか？')"
                    id="image" alt="logout" src="{% static 'img/logout.png' %}" 
                    class="logout-img">
                </form>
            
            </header>

            <main>
                {% block error %}{% endblock %}
                {% block content %}
                <p>※コンテンツがありません。</p>
                {% endblock %}
            </main>

            <footer>
                <div>
                    <p class="p-heading">Time Log Manager</p>
                </div>
                <div>
                    <nav>
                        <p>
                            <a href="{% url 'time_logging:use' %}">使い方</a>
                        </p>
                        <p>|</p>
                        <p><a href="{% url 'accounts:mypage' %}">ユーザー画面</a></p>
                    </nav>
                </div>
                <div>
                    <img src="{% static 'img/icon.png' %}" alt="現在の管理者">
                </div>
                <div style="height: 12px;"></div>
                <p>Made in KS-PF | 2023~2024</p>
                <p>All rights reserved</p>
                <div style="height: 32px;"></div>
            </footer>
        </div>
    </div>
</body>

</html>